apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: gavyasree/my-app:fbc84ad68d8236b40011034a593234e491526865
        ports:
        - containerPort: 3000

